# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/set-up-node@v2
      - name: build package
        run: npm run deploy
      - name: complate
        run: echo success,
